#!/bin/sh

# Copyright (2020) by Marcel Lambert.
# This project's License is the MIT Open Source license.
# For more information, see the LICENSE.md file in this repository.

set -e

conform enforce --commit-msg-file $1