#!/bin/sh

# Copyright (2020) by Marcel Lambert.
# This project's License is the MIT Open Source license.
# For more information, see the LICENSE.md file in this repository.

set -e

echo '+cargo fmt'
cargo fmt --all -- --check

export CARGO_INCREMENTAL=0
export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"
cargo build

echo '+cargo test --all'
cargo test --all --all-features --no-fail-fast
echo '+cargo clippy --all -- -D warnings'
cargo clippy --all -- -D warnings

cargo lichking check
