#!/bin/sh

# Copyright (2020) by Marcel Lambert.
# This project's License is the MIT Open Source license.
# For more information, see the LICENSE.md file in this repository.

set -e

echo '+cargo fmt'
cargo fmt --all -- --check
echo '+cargo test --all'
cargo test --all
echo '+cargo clippy --all -- -D warnings'
cargo clippy --all -- -D warnings

cargo lichking check