policies:
  - type: commit
    spec:
      headerLength: 89
      dco: false
      gpg: false
      imperative: true
      maximumOfOneCommit: true
      requireCommitBody: false
      conventional:
        types:
          - "build"
          - "ci"
          - "docs"
          - "feat"
          - "fix"
          - "perf"
          - "refactor"
          - "style"
          - "test"
        scopes:
          - "macro"
          - "traits"
          - "core"
        descriptionLength: 72
  - type: license
    spec:
      skipPaths:
        - .git/
        - target/
      includeSuffixes:
        - .rs
      excludeSuffixes:
        - .exclude-ext-prefix.ext
      header: |
        /*
         * Copyright (2020) by Marcel Lambert.
         * This project's License is the MIT Open Source license.
         * For more information, see the LICENSE.md file in this repository.
         */

